#!/bin/sh
# aster-agent installer — modeled on komari-agent's install script.
# Supports Linux (systemd / OpenRC) and macOS (launchd).
# Usage: curl -fsSL <raw-url>/agent/install.sh | sudo sh -s -- --token <TOKEN> [--listen :9977]
#   --token <t>       required, bearer token generated by Aster.app
#   --listen <addr>   listen address, default :9977
#   --state-dir <d>   TLS state directory, default /var/lib/aster-agent
#   --ghproxy <p>     GitHub proxy prefix, e.g. https://ghproxy.example (for CN networks)
#   --version <v>     release tag to install, default latest
#   --repo <o/r>      GitHub repository, default set below at release time
#   --sha256 <hex>    optional: verify the downloaded binary against this digest
#   --uninstall       stop the service and remove the binary
set -eu

REPO="maow318/astervps"
TOKEN=""
LISTEN=":9977"
STATE_DIR="/var/lib/aster-agent"
GHPROXY=""
VERSION="latest"
SHA256=""
UNINSTALL=0
BIN=/usr/local/bin/aster-agent
SERVICE=aster-agent
TOKEN_DIR=/etc/aster-agent
TOKEN_FILE=$TOKEN_DIR/token
PLIST=/Library/LaunchDaemons/cc.aster.agent.plist
DARWIN_LOG=/var/log/aster-agent.log

log() { printf '%s\n' "$1"; }
fail() { printf 'ERROR: %s\n' "$1" >&2; exit 1; }

while [ "$#" -gt 0 ]; do
  case "$1" in
    --token) TOKEN="$2"; shift 2 ;;
    --listen) LISTEN="$2"; shift 2 ;;
    --state-dir) STATE_DIR="$2"; shift 2 ;;
    --ghproxy) GHPROXY="$2"; shift 2 ;;
    --version) VERSION="$2"; shift 2 ;;
    --repo) REPO="$2"; shift 2 ;;
    --sha256) SHA256="$2"; shift 2 ;;
    --uninstall) UNINSTALL=1; shift ;;
    *) log "ignoring unknown argument: $1"; shift ;;
  esac
done

[ "$(id -u)" = 0 ] || fail "run as root (sudo)"

stop_previous() {
  if [ "$(uname -s)" = "Darwin" ]; then
    if [ -f "$PLIST" ]; then
      launchctl bootout system "$PLIST" 2>/dev/null || true
      rm -f "$PLIST"
    fi
    return 0
  fi
  if command -v systemctl >/dev/null 2>&1 && [ -f "/etc/systemd/system/$SERVICE.service" ]; then
    systemctl stop "$SERVICE" 2>/dev/null || true
    systemctl disable "$SERVICE" 2>/dev/null || true
    rm -f "/etc/systemd/system/$SERVICE.service"
    systemctl daemon-reload
  elif command -v rc-service >/dev/null 2>&1 && [ -f "/etc/init.d/$SERVICE" ]; then
    rc-service "$SERVICE" stop 2>/dev/null || true
    rc-update del "$SERVICE" default 2>/dev/null || true
    rm -f "/etc/init.d/$SERVICE"
  fi
}

if [ "$UNINSTALL" = 1 ]; then
  stop_previous
  rm -f "$BIN" "$TOKEN_FILE"
  rmdir "$TOKEN_DIR" 2>/dev/null || true
  log "aster-agent uninstalled (state dir $STATE_DIR kept; remove manually if desired)"
  exit 0
fi

[ -n "$TOKEN" ] || fail "--token is required"
[ "$REPO" != "ASTER_REPO_PLACEHOLDER" ] || fail "release repository not configured yet; pass --repo <owner>/<repo> or install manually (see agent/README.md)"
command -v curl >/dev/null 2>&1 || fail "curl is required; install it with your package manager"

case "$(uname -s)" in
  Linux) PLATFORM=linux ;;
  Darwin) PLATFORM=darwin ;;
  *) fail "unsupported system: $(uname -s)" ;;
esac

case "$(uname -m)" in
  x86_64) ARCH=amd64 ;;
  aarch64 | arm64) ARCH=arm64 ;;
  armv7* | armv6*) ARCH=arm ;;
  i386 | i686) ARCH=386 ;;
  *) fail "unsupported architecture: $(uname -m)" ;;
esac

ASSET="aster-agent-$PLATFORM-$ARCH"
if [ "$VERSION" = "latest" ]; then
  URL="https://github.com/$REPO/releases/latest/download/$ASSET"
else
  URL="https://github.com/$REPO/releases/download/$VERSION/$ASSET"
fi
# Until a GitHub release with assets exists, binaries are served from the
# repository's `dist` branch; the release URL is preferred once it works.
FALLBACK_URL="https://raw.githubusercontent.com/$REPO/dist/$ASSET"
if [ -n "$GHPROXY" ]; then
  URL="$GHPROXY/$URL"
  FALLBACK_URL="$GHPROXY/$FALLBACK_URL"
fi

stop_previous

log "downloading $URL"
if ! curl -fL -o "$BIN.tmp" "$URL"; then
  log "release download unavailable, falling back to $FALLBACK_URL"
  curl -fL -o "$BIN.tmp" "$FALLBACK_URL" || fail "download failed"
fi
if [ -n "$SHA256" ]; then
  if command -v sha256sum >/dev/null 2>&1; then
    ACTUAL=$(sha256sum "$BIN.tmp" | cut -d' ' -f1)
  else
    ACTUAL=$(shasum -a 256 "$BIN.tmp" | cut -d' ' -f1)
  fi
  [ "$ACTUAL" = "$SHA256" ] || { rm -f "$BIN.tmp"; fail "sha256 mismatch: got $ACTUAL"; }
  log "sha256 verified"
fi
mkdir -p "$(dirname "$BIN")"
chmod 755 "$BIN.tmp"
mv "$BIN.tmp" "$BIN"

mkdir -p "$STATE_DIR"

# The token lives in a root-only file instead of the unit's command line, so
# it never shows up in `ps` output or the world-readable unit file.
mkdir -p "$TOKEN_DIR"
umask_previous=$(umask)
umask 077
printf '%s' "$TOKEN" > "$TOKEN_FILE"
umask "$umask_previous"
chmod 600 "$TOKEN_FILE"

if [ "$PLATFORM" = "darwin" ]; then
  cat > "$PLIST" << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>cc.aster.agent</string>
  <key>ProgramArguments</key>
  <array>
    <string>$BIN</string>
    <string>--listen</string><string>$LISTEN</string>
    <string>--token-file</string><string>$TOKEN_FILE</string>
    <string>--state-dir</string><string>$STATE_DIR</string>
  </array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>StandardOutPath</key><string>$DARWIN_LOG</string>
  <key>StandardErrorPath</key><string>$DARWIN_LOG</string>
</dict>
</plist>
EOF
  launchctl bootstrap system "$PLIST"
  sleep 2
  FINGERPRINT=$(grep -o 'fingerprint: [0-9a-f]*' "$DARWIN_LOG" 2>/dev/null | tail -1 | cut -d' ' -f2 || true)
elif command -v systemctl >/dev/null 2>&1 && [ -d /run/systemd/system ]; then
  cat > "/etc/systemd/system/$SERVICE.service" << EOF
[Unit]
Description=Aster Agent
After=network-online.target

[Service]
ExecStart=$BIN --listen $LISTEN --token-file $TOKEN_FILE --state-dir $STATE_DIR
Restart=always
RestartSec=3
# Hardening: the agent only reads system state; it never needs new privileges,
# a writable /usr//etc, or anyone's home directory.
NoNewPrivileges=yes
ProtectSystem=full
ProtectHome=read-only
PrivateTmp=yes
ProtectKernelTunables=yes
ProtectControlGroups=yes
RestrictSUIDSGID=yes

[Install]
WantedBy=multi-user.target
EOF
  systemctl daemon-reload
  systemctl enable --now "$SERVICE"
  sleep 2
  FINGERPRINT=$(journalctl -u "$SERVICE" --no-pager 2>/dev/null | grep -o 'fingerprint: [0-9a-f]*' | tail -1 | cut -d' ' -f2 || true)
elif command -v rc-service >/dev/null 2>&1; then
  cat > "/etc/init.d/$SERVICE" << EOF
#!/sbin/openrc-run
name="Aster Agent"
command="$BIN"
command_args="--listen $LISTEN --token-file $TOKEN_FILE --state-dir $STATE_DIR"
command_background=true
pidfile="/run/$SERVICE.pid"
output_log="/var/log/$SERVICE.log"
error_log="/var/log/$SERVICE.log"
depend() { need net; }
EOF
  chmod +x "/etc/init.d/$SERVICE"
  rc-update add "$SERVICE" default
  rc-service "$SERVICE" start
  sleep 2
  FINGERPRINT=$(grep -o 'fingerprint: [0-9a-f]*' "/var/log/$SERVICE.log" 2>/dev/null | tail -1 | cut -d' ' -f2 || true)
else
  fail "no supported init system found (systemd or OpenRC)"
fi

log ""
log "=========================================="
log "aster-agent installed and running on $LISTEN"
if [ -n "${FINGERPRINT:-}" ]; then
  log "TLS SHA-256 fingerprint (compare in Aster.app):"
  log "  $FINGERPRINT"
elif [ "$PLATFORM" = "darwin" ]; then
  log "fingerprint not captured yet; view it with:"
  log "  grep fingerprint $DARWIN_LOG"
else
  log "fingerprint not captured yet; view it with:"
  log "  journalctl -u $SERVICE | grep fingerprint"
fi
log "=========================================="
