#!/bin/sh
# aster-agent installer — modeled on komari-agent's install script.
# Usage: curl -fsSL <raw-url>/agent/install.sh | sh -s -- --token <TOKEN> [--listen :9977]
#   --token <t>       required, bearer token generated by Aster.app
#   --listen <addr>   listen address, default :9977
#   --state-dir <d>   TLS state directory, default /var/lib/aster-agent
#   --ghproxy <p>     GitHub proxy prefix, e.g. https://ghproxy.example (for CN networks)
#   --version <v>     release tag to install, default latest
#   --repo <o/r>      GitHub repository, default set below at release time
#   --uninstall       stop the service and remove the binary
set -eu

REPO="ASTER_REPO_PLACEHOLDER"
TOKEN=""
LISTEN=":9977"
STATE_DIR="/var/lib/aster-agent"
GHPROXY=""
VERSION="latest"
UNINSTALL=0
BIN=/usr/local/bin/aster-agent
SERVICE=aster-agent

log() { printf '%s\n' "$1"; }
fail() { printf 'ERROR: %s\n' "$1" >&2; exit 1; }

while [ "$#" -gt 0 ]; do
  case "$1" in
    --token) TOKEN="$2"; shift 2 ;;
    --listen) LISTEN="$2"; shift 2 ;;
    --state-dir) STATE_DIR="$2"; shift 2 ;;
    --ghproxy) GHPROXY="$2"; shift 2 ;;
    --version) VERSION="$2"; shift 2 ;;
    --repo) REPO="$2"; shift 2 ;;
    --uninstall) UNINSTALL=1; shift ;;
    *) log "ignoring unknown argument: $1"; shift ;;
  esac
done

[ "$(id -u)" = 0 ] || fail "run as root (sudo)"

stop_previous() {
  if command -v systemctl >/dev/null 2>&1 && [ -f "/etc/systemd/system/$SERVICE.service" ]; then
    systemctl stop "$SERVICE" 2>/dev/null || true
    systemctl disable "$SERVICE" 2>/dev/null || true
    rm -f "/etc/systemd/system/$SERVICE.service"
    systemctl daemon-reload
  elif command -v rc-service >/dev/null 2>&1 && [ -f "/etc/init.d/$SERVICE" ]; then
    rc-service "$SERVICE" stop 2>/dev/null || true
    rc-update del "$SERVICE" default 2>/dev/null || true
    rm -f "/etc/init.d/$SERVICE"
  fi
}

if [ "$UNINSTALL" = 1 ]; then
  stop_previous
  rm -f "$BIN"
  log "aster-agent uninstalled (state dir $STATE_DIR kept; remove manually if desired)"
  exit 0
fi

[ -n "$TOKEN" ] || fail "--token is required"
[ "$REPO" != "ASTER_REPO_PLACEHOLDER" ] || fail "release repository not configured yet; pass --repo <owner>/<repo> or install manually (see agent/README.md)"
command -v curl >/dev/null 2>&1 || fail "curl is required; install it with your package manager"
[ "$(uname -s)" = "Linux" ] || fail "this installer supports Linux; see agent/README.md for other systems"

case "$(uname -m)" in
  x86_64) ARCH=amd64 ;;
  aarch64 | arm64) ARCH=arm64 ;;
  armv7* | armv6*) ARCH=arm ;;
  i386 | i686) ARCH=386 ;;
  *) fail "unsupported architecture: $(uname -m)" ;;
esac

if [ "$VERSION" = "latest" ]; then
  URL="https://github.com/$REPO/releases/latest/download/aster-agent-linux-$ARCH"
else
  URL="https://github.com/$REPO/releases/download/$VERSION/aster-agent-linux-$ARCH"
fi
[ -z "$GHPROXY" ] || URL="$GHPROXY/$URL"

stop_previous

log "downloading $URL"
curl -fL -o "$BIN.tmp" "$URL" || fail "download failed"
chmod 755 "$BIN.tmp"
mv "$BIN.tmp" "$BIN"

mkdir -p "$STATE_DIR"

if command -v systemctl >/dev/null 2>&1 && [ -d /run/systemd/system ]; then
  cat > "/etc/systemd/system/$SERVICE.service" << EOF
[Unit]
Description=Aster Agent
After=network-online.target

[Service]
ExecStart=$BIN --listen $LISTEN --token $TOKEN --state-dir $STATE_DIR
Restart=always
RestartSec=3

[Install]
WantedBy=multi-user.target
EOF
  systemctl daemon-reload
  systemctl enable --now "$SERVICE"
  sleep 2
  FINGERPRINT=$(journalctl -u "$SERVICE" --no-pager 2>/dev/null | grep -o 'fingerprint: [0-9a-f]*' | tail -1 | cut -d' ' -f2 || true)
elif command -v rc-service >/dev/null 2>&1; then
  cat > "/etc/init.d/$SERVICE" << EOF
#!/sbin/openrc-run
name="Aster Agent"
command="$BIN"
command_args="--listen $LISTEN --token $TOKEN --state-dir $STATE_DIR"
command_background=true
pidfile="/run/$SERVICE.pid"
output_log="/var/log/$SERVICE.log"
error_log="/var/log/$SERVICE.log"
depend() { need net; }
EOF
  chmod +x "/etc/init.d/$SERVICE"
  rc-update add "$SERVICE" default
  rc-service "$SERVICE" start
  sleep 2
  FINGERPRINT=$(grep -o 'fingerprint: [0-9a-f]*' "/var/log/$SERVICE.log" 2>/dev/null | tail -1 | cut -d' ' -f2 || true)
else
  fail "no supported init system found (systemd or OpenRC)"
fi

log ""
log "=========================================="
log "aster-agent installed and running on $LISTEN"
if [ -n "${FINGERPRINT:-}" ]; then
  log "TLS SHA-256 fingerprint (compare in Aster.app):"
  log "  $FINGERPRINT"
else
  log "fingerprint not captured yet; view it with:"
  log "  journalctl -u $SERVICE | grep fingerprint"
fi
log "=========================================="
