#!/bin/sh
# aster-agent installer — modeled on komari-agent's install script.
# Supports Linux (systemd / OpenRC) and macOS (launchd).
# Usage: curl -fsSL <raw-url>/agent/install.sh | sudo sh -s -- --token <TOKEN> [--listen :9977]
#   --token <t>       required, bearer token generated by Aster.app
#   --listen <addr>   listen address, default :9977
#   --state-dir <d>   TLS state directory, default /var/lib/aster-agent
#   --ghproxy <p>     GitHub proxy prefix, e.g. https://ghproxy.example (for CN networks)
#   --version <v>     release tag to install, default latest
#   --repo <o/r>      GitHub repository, default set below at release time
#   --sha256 <hex>    optional: verify the downloaded binary against this digest
#   --domain <d>      Linux only: hide the agent behind a real domain on 443.
#                     PREREQUISITE: the domain's A record must already point at
#                     this server (or be proxied through Cloudflare). The agent
#                     then listens on loopback only and Caddy/nginx terminates
#                     TLS with a CA certificate — in Aster.app just enter
#                     https://<domain>, no fingerprint needed.
#   --proxy <p>       caddy | nginx | auto (default auto: existing caddy >
#                     existing nginx > install caddy)
#   --uninstall       stop the service, remove the binary and any proxy block
set -eu

REPO="maow318/astervps"
TOKEN=""
LISTEN=":9977"
STATE_DIR="/var/lib/aster-agent"
GHPROXY=""
VERSION="latest"
SHA256=""
DOMAIN=""
PROXY="auto"
UNINSTALL=0
NGINX_CONF=/etc/nginx/conf.d/aster-agent.conf
CADDYFILE=/etc/caddy/Caddyfile
BIN=/usr/local/bin/aster-agent
SERVICE=aster-agent
TOKEN_DIR=/etc/aster-agent
TOKEN_FILE=$TOKEN_DIR/token
PLIST=/Library/LaunchDaemons/cc.aster.agent.plist
DARWIN_LOG=/var/log/aster-agent.log

log() { printf '%s\n' "$1"; }
fail() { printf 'ERROR: %s\n' "$1" >&2; exit 1; }

while [ "$#" -gt 0 ]; do
  case "$1" in
    --token) TOKEN="$2"; shift 2 ;;
    --listen) LISTEN="$2"; shift 2 ;;
    --state-dir) STATE_DIR="$2"; shift 2 ;;
    --ghproxy) GHPROXY="$2"; shift 2 ;;
    --version) VERSION="$2"; shift 2 ;;
    --repo) REPO="$2"; shift 2 ;;
    --sha256) SHA256="$2"; shift 2 ;;
    --domain) DOMAIN="$2"; shift 2 ;;
    --proxy) PROXY="$2"; shift 2 ;;
    --uninstall) UNINSTALL=1; shift ;;
    *) log "ignoring unknown argument: $1"; shift ;;
  esac
done

[ "$(id -u)" = 0 ] || fail "run as root (sudo)"

stop_previous() {
  if [ "$(uname -s)" = "Darwin" ]; then
    if [ -f "$PLIST" ]; then
      launchctl bootout system "$PLIST" 2>/dev/null || true
      rm -f "$PLIST"
    fi
    return 0
  fi
  if command -v systemctl >/dev/null 2>&1 && [ -f "/etc/systemd/system/$SERVICE.service" ]; then
    systemctl stop "$SERVICE" 2>/dev/null || true
    systemctl disable "$SERVICE" 2>/dev/null || true
    rm -f "/etc/systemd/system/$SERVICE.service"
    systemctl daemon-reload
  elif command -v rc-service >/dev/null 2>&1 && [ -f "/etc/init.d/$SERVICE" ]; then
    rc-service "$SERVICE" stop 2>/dev/null || true
    rc-update del "$SERVICE" default 2>/dev/null || true
    rm -f "/etc/init.d/$SERVICE"
  fi
}

remove_proxy_config() {
  if [ -f "$CADDYFILE" ] && grep -q '# aster-agent begin' "$CADDYFILE" 2>/dev/null; then
    sed -i '/# aster-agent begin/,/# aster-agent end/d' "$CADDYFILE"
    systemctl reload caddy 2>/dev/null || true
  fi
  if [ -f "$NGINX_CONF" ]; then
    rm -f "$NGINX_CONF"
    systemctl reload nginx 2>/dev/null || true
  fi
}

if [ "$UNINSTALL" = 1 ]; then
  stop_previous
  [ "$(uname -s)" = "Linux" ] && remove_proxy_config
  rm -f "$BIN" "$TOKEN_FILE"
  rmdir "$TOKEN_DIR" 2>/dev/null || true
  log "aster-agent uninstalled (state dir $STATE_DIR kept; remove manually if desired)"
  exit 0
fi

[ -n "$TOKEN" ] || fail "--token is required"
[ "$REPO" != "ASTER_REPO_PLACEHOLDER" ] || fail "release repository not configured yet; pass --repo <owner>/<repo> or install manually (see agent/README.md)"
command -v curl >/dev/null 2>&1 || fail "curl is required; install it with your package manager"

case "$(uname -s)" in
  Linux) PLATFORM=linux ;;
  Darwin) PLATFORM=darwin ;;
  *) fail "unsupported system: $(uname -s)" ;;
esac

case "$(uname -m)" in
  x86_64) ARCH=amd64 ;;
  aarch64 | arm64) ARCH=arm64 ;;
  armv7* | armv6*) ARCH=arm ;;
  i386 | i686) ARCH=386 ;;
  *) fail "unsupported architecture: $(uname -m)" ;;
esac

# ---- domain mode pre-flight -------------------------------------------------
if [ -n "$DOMAIN" ]; then
  [ "$PLATFORM" = "linux" ] || fail "--domain mode is Linux-only (the local Mac never needs it)"
  case "$PROXY" in caddy|nginx|auto) ;; *) fail "--proxy must be caddy, nginx or auto" ;; esac
  # The agent must not stay exposed on the public interface in domain mode.
  AGENT_PORT="${LISTEN##*:}"
  LISTEN="127.0.0.1:$AGENT_PORT"

  log "domain mode: $DOMAIN (agent will listen on loopback only)"
  log "prerequisite: the domain's A record must already point at this server,"
  log "or be proxied through a CDN such as Cloudflare."
  RESOLVED=$(getent ahosts "$DOMAIN" 2>/dev/null | awk '{print $1; exit}' || true)
  if [ -z "$RESOLVED" ]; then
    PUBLIC_IP=$(curl -4fsS --max-time 8 https://api.ipify.org 2>/dev/null || true)
    fail "cannot resolve $DOMAIN — add an A record first: $DOMAIN -> ${PUBLIC_IP:-your-server-IP}"
  fi
  PUBLIC_IP=$(curl -4fsS --max-time 8 https://api.ipify.org 2>/dev/null || true)
  if [ -n "$PUBLIC_IP" ] && [ "$RESOLVED" != "$PUBLIC_IP" ]; then
    log "NOTE: $DOMAIN resolves to $RESOLVED but this server's IP is $PUBLIC_IP."
    log "      Expected if the domain is behind a CDN proxy (Cloudflare); otherwise fix the A record."
  fi
fi

ASSET="aster-agent-$PLATFORM-$ARCH"
if [ "$VERSION" = "latest" ]; then
  URL="https://github.com/$REPO/releases/latest/download/$ASSET"
else
  URL="https://github.com/$REPO/releases/download/$VERSION/$ASSET"
fi
# Until a GitHub release with assets exists, binaries are served from the
# repository's `dist` branch; the release URL is preferred once it works.
FALLBACK_URL="https://raw.githubusercontent.com/$REPO/dist/$ASSET"
if [ -n "$GHPROXY" ]; then
  URL="$GHPROXY/$URL"
  FALLBACK_URL="$GHPROXY/$FALLBACK_URL"
fi

stop_previous

log "downloading $URL"
if ! curl -fL -o "$BIN.tmp" "$URL"; then
  log "release download unavailable, falling back to $FALLBACK_URL"
  curl -fL -o "$BIN.tmp" "$FALLBACK_URL" || fail "download failed"
fi
if [ -n "$SHA256" ]; then
  if command -v sha256sum >/dev/null 2>&1; then
    ACTUAL=$(sha256sum "$BIN.tmp" | cut -d' ' -f1)
  else
    ACTUAL=$(shasum -a 256 "$BIN.tmp" | cut -d' ' -f1)
  fi
  [ "$ACTUAL" = "$SHA256" ] || { rm -f "$BIN.tmp"; fail "sha256 mismatch: got $ACTUAL"; }
  log "sha256 verified"
fi
mkdir -p "$(dirname "$BIN")"
chmod 755 "$BIN.tmp"
mv "$BIN.tmp" "$BIN"

mkdir -p "$STATE_DIR"

# The token lives in a root-only file instead of the unit's command line, so
# it never shows up in `ps` output or the world-readable unit file.
mkdir -p "$TOKEN_DIR"
umask_previous=$(umask)
umask 077
printf '%s' "$TOKEN" > "$TOKEN_FILE"
umask "$umask_previous"
chmod 600 "$TOKEN_FILE"

if [ "$PLATFORM" = "darwin" ]; then
  cat > "$PLIST" << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>cc.aster.agent</string>
  <key>ProgramArguments</key>
  <array>
    <string>$BIN</string>
    <string>--listen</string><string>$LISTEN</string>
    <string>--token-file</string><string>$TOKEN_FILE</string>
    <string>--state-dir</string><string>$STATE_DIR</string>
  </array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>StandardOutPath</key><string>$DARWIN_LOG</string>
  <key>StandardErrorPath</key><string>$DARWIN_LOG</string>
</dict>
</plist>
EOF
  launchctl bootstrap system "$PLIST"
  sleep 2
  FINGERPRINT=$(grep -o 'fingerprint: [0-9a-f]*' "$DARWIN_LOG" 2>/dev/null | tail -1 | cut -d' ' -f2 || true)
elif command -v systemctl >/dev/null 2>&1 && [ -d /run/systemd/system ]; then
  cat > "/etc/systemd/system/$SERVICE.service" << EOF
[Unit]
Description=Aster Agent
After=network-online.target

[Service]
ExecStart=$BIN --listen $LISTEN --token-file $TOKEN_FILE --state-dir $STATE_DIR
Restart=always
RestartSec=3
# Hardening: the agent only reads system state; it never needs new privileges,
# a writable /usr//etc, or anyone's home directory.
NoNewPrivileges=yes
ProtectSystem=full
ProtectHome=read-only
PrivateTmp=yes
ProtectKernelTunables=yes
ProtectControlGroups=yes
RestrictSUIDSGID=yes

[Install]
WantedBy=multi-user.target
EOF
  systemctl daemon-reload
  systemctl enable --now "$SERVICE"
  sleep 2
  FINGERPRINT=$(journalctl -u "$SERVICE" --no-pager 2>/dev/null | grep -o 'fingerprint: [0-9a-f]*' | tail -1 | cut -d' ' -f2 || true)
elif command -v rc-service >/dev/null 2>&1; then
  cat > "/etc/init.d/$SERVICE" << EOF
#!/sbin/openrc-run
name="Aster Agent"
command="$BIN"
command_args="--listen $LISTEN --token-file $TOKEN_FILE --state-dir $STATE_DIR"
command_background=true
pidfile="/run/$SERVICE.pid"
output_log="/var/log/$SERVICE.log"
error_log="/var/log/$SERVICE.log"
depend() { need net; }
EOF
  chmod +x "/etc/init.d/$SERVICE"
  rc-update add "$SERVICE" default
  rc-service "$SERVICE" start
  sleep 2
  FINGERPRINT=$(grep -o 'fingerprint: [0-9a-f]*' "/var/log/$SERVICE.log" 2>/dev/null | tail -1 | cut -d' ' -f2 || true)
else
  fail "no supported init system found (systemd or OpenRC)"
fi

# ---- domain mode: reverse proxy + real certificate --------------------------
setup_caddy() {
  if ! command -v caddy >/dev/null 2>&1; then
    log "installing Caddy (official repository)"
    command -v apt-get >/dev/null 2>&1 || fail "automatic Caddy install needs apt; install caddy or nginx manually, then re-run"
    apt-get update -qq
    apt-get install -y -qq debian-keyring debian-archive-keyring apt-transport-https gnupg >/dev/null
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' \
      | gpg --dearmor --yes -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' \
      > /etc/apt/sources.list.d/caddy-stable.list
    apt-get update -qq && apt-get install -y -qq caddy >/dev/null
  fi
  touch "$CADDYFILE"
  sed -i '/# aster-agent begin/,/# aster-agent end/d' "$CADDYFILE"
  cat >> "$CADDYFILE" << EOF
# aster-agent begin
$DOMAIN {
  reverse_proxy https://127.0.0.1:$AGENT_PORT {
    transport http {
      tls_insecure_skip_verify
    }
  }
}
# aster-agent end
EOF
  systemctl enable --now caddy >/dev/null 2>&1 || true
  systemctl reload caddy 2>/dev/null || systemctl restart caddy
  log "Caddy configured; the certificate is issued and renewed automatically."
}

setup_nginx() {
  cat > "$NGINX_CONF" << EOF
server {
    listen 80;
    server_name $DOMAIN;
    location / {
        proxy_pass https://127.0.0.1:$AGENT_PORT;
        proxy_ssl_verify off;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
    }
}
EOF
  nginx -t || fail "nginx config test failed"
  systemctl reload nginx 2>/dev/null || systemctl restart nginx
  if ! command -v certbot >/dev/null 2>&1; then
    log "installing certbot"
    if command -v apt-get >/dev/null 2>&1; then
      apt-get update -qq && apt-get install -y -qq certbot python3-certbot-nginx >/dev/null
    elif command -v dnf >/dev/null 2>&1; then
      dnf install -y -q certbot python3-certbot-nginx
    else
      fail "certbot unavailable; install it manually, then run: certbot --nginx -d $DOMAIN"
    fi
  fi
  certbot --nginx -d "$DOMAIN" --non-interactive --agree-tos --register-unsafely-without-email \
    || fail "certificate issuance failed (is port 80 reachable and DNS live?); fix and re-run: certbot --nginx -d $DOMAIN"
  log "nginx + Let's Encrypt configured; certbot renews automatically."
}

if [ -n "$DOMAIN" ]; then
  case "$PROXY" in
    caddy) setup_caddy ;;
    nginx) setup_nginx ;;
    auto)
      if command -v caddy >/dev/null 2>&1; then setup_caddy
      elif command -v nginx >/dev/null 2>&1; then setup_nginx
      else setup_caddy
      fi
      ;;
  esac
fi

log ""
log "=========================================="
log "aster-agent installed and running on $LISTEN"
if [ -n "$DOMAIN" ]; then
  log "Domain mode active. In Aster.app add this machine with:"
  log "  https://$DOMAIN"
  log "No fingerprint comparison needed — the CA certificate is verified automatically."
elif [ -n "${FINGERPRINT:-}" ]; then
  log "TLS SHA-256 fingerprint (compare in Aster.app):"
  log "  $FINGERPRINT"
elif [ "$PLATFORM" = "darwin" ]; then
  log "fingerprint not captured yet; view it with:"
  log "  grep fingerprint $DARWIN_LOG"
else
  log "fingerprint not captured yet; view it with:"
  log "  journalctl -u $SERVICE | grep fingerprint"
fi
log "=========================================="
